/**
 * WorkOrderCardComponent
 *
 * Reusable card component for displaying a visual summary of a work order.
 * It is mainly used in work order list views to show the tracking code,
 * vehicle, customer, progress, dates, status, price and risk information.
 *
 * The component emits the original work order when the user requests
 * to view the complete detail.
 *
 * @component
 * @selector app-work-order-card
 * @standalone true
 */
import { CommonModule, CurrencyPipe } from '@angular/common';
import { Component, EventEmitter, Input, Output } from '@angular/core';

import { MatButtonModule } from '@angular/material/button';
import { MatIconModule } from '@angular/material/icon';
import { MatProgressBarModule } from '@angular/material/progress-bar';

import { TranslateModule } from '@ngx-translate/core';

import { WorkOrder } from '../../../../domain/models/work-order.model';

/**
 * WorkOrderCardView
 *
 * View model used by WorkOrderCardComponent to render enriched work order data.
 * It combines the original WorkOrder domain model with additional display
 * values such as vehicle name, plate, customer name, progress and risk status.
 */
export interface WorkOrderCardView {
  /**
   * Unique work order identifier.
   */
  id: string;

  /**
   * Original work order domain model.
   */
  raw: WorkOrder;

  /**
   * Public tracking code used by the customer or workshop.
   */
  trackingCode: string;

  /**
   * Vehicle name associated with the order.
   */
  vehicleName: string;

  /**
   * Vehicle plate associated with the order.
   */
  plateOnly: string;

  /**
   * Customer name associated with the order.
   */
  customerName: string;

  /**
   * Work order progress percentage.
   */
  progress: number;

  /**
   * Work order start date.
   */
  startDate: string;

  /**
   * Estimated delivery or completion date.
   */
  estimatedDate: string;

  /**
   * Current work order status.
   */
  status: WorkOrder['status'];

  /**
   * Total work order price.
   */
  price: number;

  /**
   * Indicates whether the order has delivery or operational risk.
   */
  isRisk: boolean;

  /**
   * Human-readable risk status.
   */
  riskStatus: string;

  /**
   * CSS class used to style the risk indicator.
   */
  riskClass: string;
}

@Component({
  selector: 'app-work-order-card',
  standalone: true,
  imports: [
    CommonModule,
    CurrencyPipe,
    MatButtonModule,
    MatIconModule,
    MatProgressBarModule,
    TranslateModule
  ],
  templateUrl: './work-order-card.html',
  styleUrl: './work-order-card.css'
})
export class WorkOrderCardComponent {

  /**
   * Work order data displayed by the card.
   */
  @Input({ required: true }) order!: WorkOrderCardView;

  /**
   * Event emitted when the user clicks the view details button.
   */
  @Output() viewDetail = new EventEmitter<WorkOrder>();

  /**
   * Emits the original work order to the parent component.
   */
  protected onViewDetail(): void {
    this.viewDetail.emit(this.order.raw);
  }

  /**
   * Returns the CSS class based on the current work order status.
   *
   * @param status Current work order status.
   * @returns CSS class for the status badge.
   */
  protected getStatusClass(status: WorkOrder['status']): string {
    if (status === 'Finalizado') return 'status-success';
    if (status === 'Cancelado') return 'status-danger';
    if (status === 'Pendiente') return 'status-warning';

    return 'status-info';
  }

  /**
   * Returns the translation key for the current work order status.
   *
   * @param status Current work order status.
   * @returns Translation key for the status label.
   */
  protected getStatusTranslationKey(status: WorkOrder['status']): string {
    if (status === 'Pendiente') return 'WORK_ORDER_CARD.STATUS.PENDING';
    if (status === 'En Proceso') return 'WORK_ORDER_CARD.STATUS.IN_PROGRESS';
    if (status === 'Finalizado') return 'WORK_ORDER_CARD.STATUS.FINISHED';
    if (status === 'Cancelado') return 'WORK_ORDER_CARD.STATUS.CANCELLED';

    return 'WORK_ORDER_CARD.STATUS.UNKNOWN';
  }

  /**
   * Returns the translation key for the current risk status.
   *
   * @param riskStatus Risk status value generated by the parent component.
   * @returns Translation key for the risk status label.
   */
  protected getRiskStatusTranslationKey(riskStatus: string): string {
    if (riskStatus === 'A tiempo' || riskStatus === 'On Time') {
      return 'WORK_ORDER_CARD.RISK_STATUS.ON_TIME';
    }

    if (riskStatus === 'En riesgo' || riskStatus === 'At Risk') {
      return 'WORK_ORDER_CARD.RISK_STATUS.AT_RISK';
    }

    if (
      riskStatus === 'Retrasada' ||
      riskStatus === 'Atrasado' ||
      riskStatus === 'Delayed' ||
      riskStatus === 'Overdue'
    ) {
      return 'WORK_ORDER_CARD.RISK_STATUS.OVERDUE';
    }

    if (riskStatus === 'Completada' || riskStatus === 'Completed') {
      return 'WORK_ORDER_CARD.RISK_STATUS.COMPLETED';
    }

    if (riskStatus === 'Cancelada' || riskStatus === 'Cancelled') {
      return 'WORK_ORDER_CARD.RISK_STATUS.CANCELLED';
    }

    return 'WORK_ORDER_CARD.RISK_STATUS.UNKNOWN';
  }
}