/**
 * Interface that represents a Mechanic in the system.
 * 
 * Contains the basic information of mechanics who work in the workshop,
 * including their specialty, availability, and work capacity.
 * 
 * @interface
 * @model
 */
export interface Mechanic {

  /** Unique ID of the mechanic (generated by json-server) */
  id?: string;

  /** Full name of the mechanic */
  fullName: string;

  /** Main specialty of the mechanic (e.g., Engine, Suspension, Electrical, etc.) */
  specialty: string;

  /** Contact phone number */
  phone?: string;

  /** Current status of the mechanic */
  status?: 'Disponible' | 'Ocupado';

  /** Maximum capacity for simultaneous work orders (optional) */
  maxCapacity?: number;
}
