/**
 * Interface that represents a Vehicle in the system.
 * 
 * Contains the main information of the vehicles that enter
 * the mechanic shop and their relationship with the owner client.
 * 
 * @interface
 * @model
 */

export interface Vehicle {
  /** Unique ID of the vehicle (generated by json-server) */
  id?: string;
  
  /** ID of the workshop to which this vehicle belongs */
  workshopId?: string;

  /** License plate of the vehicle (unique and identifying) */
  plate: string;

  /** Brand of the vehicle */
  brand: string;

  /** Model of the vehicle */
  model: string;

  /** Year of manufacture */
  year: string;

  /** Color of the vehicle */
  color: string;

  /** Current status of the vehicle in the workshop */
  status: 'En Taller' | 'Listo' | 'Entregado';

  /** ID of the owner client of the vehicle */
  customerId: string;
}
